### ISSUE TITLE
Protect the form from spam

### ISSUE THREAD

**Issue by hortongn** [uclibs/aaec#10]
Determine the spam risk for this form and come up with a light solution to deter it.

We probably don't need a full captcha, but something to outsmart most bots.

**Comment by bsp3ars** [comment]
After a conversation with @hortongn , we agreed that this is most likely not going to become an issue. It may be prudent to work on this just in case it does become an issue, but only if more time is available.

**Comment by hortongn** [comment]
There were no spam issues and the form is now closed.
