### ISSUE TITLE
Remove start-aaec.sh script

### ISSUE THREAD

**Issue by crowesn** [uclibs/aaec#160]
~~I think we want to copy over the capistrano/deploy patterns from the treatment_database:~~
~~https://github.com/uclibs/treatment_database/blob/qa/scripts/start_qp.sh~~

~~1. On libappstest/libapps2, change aaec service to mirror that of the treatment database `/etc/systemd/system/puma-treatment-database.service`~~
~~2. Copy patterns in treatment app for `scripts/start_qp.sh`~~
~~3. Use updated `start_qp.sh` instead of `start_aaec.sh` for startup?~~

Created https://github.com/uclibs/aaec/issues/214 for deploy script/puma updates.

**Comment by Janell-Huyck** [comment]
The start-aaec.sh script is now obsolete and not being called since we are running puma through a service instead of as a daemon task.  Remove the script.
