### ISSUE TITLE
QA : certificate verify failed after submitting publication

### ISSUE THREAD

**Issue by scherztc** [uclibs/aaec#162]
500 error in the rails log.
 

I, [2022-11-16T13:18:52.536744 #1116088]  INFO -- : [553f2d8d-9a9c-4031-b608-a90d7f8a5744] Completed 500 Internal Server Error in 65ms (ActiveRecord: 3.9ms | Allocations: 9207)

F, [2022-11-16T13:18:52.537561 #1116088] FATAL -- : [553f2d8d-9a9c-4031-b608-a90d7f8a5744]   

[553f2d8d-9a9c-4031-b608-a90d7f8a5744] OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate)):

https://github.com/uclibs/aaec/blob/qa/app/controllers/publications_controller.rb#L101

Possible Solution : http://railsapps.github.io/openssl-certificate-verify-failed.html

**Comment by lisa3711** [comment]
On local, I do not get the error above. In checking, locally I am using 
lisa@UCL-M403ML7L aaec % openssl version
LibreSSL 2.8.3
-------------------
On libapps test: 
[haitzlm@ad.uc.edu@libappstest ~]$ openssl version
OpenSSL 1.1.1k  FIPS 25 Mar 2021

**Comment by Janell-Huyck** [comment]
See outlook discussion [here](https://teams.microsoft.com/l/message/19:93d7555d783b4397aa7814cfe8e70c0d@thread.skype/1695752889371?tenantId=f5222e6c-5fc6-48eb-8f03-73db18203b63&groupId=05379e3e-d136-48a1-ba71-81ecaf83cfab&parentMessageId=1695752889371&teamName=UCL%20Application%20Development%20Unit&channelName=aaec&createdTime=1695752889371&allowXTenantAccess=false) for more information.

There are a total of three expired certificates related to mail in libapps and libappstest.  Libapps has en expired postfix.pem and an expired sendmail.pem.  Libappstest has an expired postfix.pem but doesn't have a sendmail.pem certificate.  I'm communicating with Samantha about this expect that getting these certificates updated will solve the problem for another year.
