### ISSUE TITLE
404 on Submission with URL

### ISSUE THREAD

**Issue by scherztc** [uclibs/aaec#239]
### Descriptive summary

Regardless of publications

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related issues or prior related work here.

**Comment by Janell-Huyck** [comment]
Submission of a digital work, including url, on libappstest, went to the 404 page.

**Comment by Janell-Huyck** [comment]
This is happening due to the fact that the qa branch currently on libappstest cannot send emails and instead triggers a 500 error (see issue #162 ).  500 errors are intentionally redirecting to the 404 page.  There is nothing to fix on this aside from having PR #233 merged into qa.
