### ISSUE TITLE
Issue and Volume don't persist in Editing publication type

### ISSUE THREAD

**Issue by crowesn** [uclibs/aaec#391]
### Descriptive summary
Issue and Volume don't persist in Editing publication type

### Expected behavior
Filling out Issue and Volume values in the create or edit form for Editing publication type should result in those values persisting to object.

### Actual behavior
Volume and Issue values remain blank.

It looks like these params need to be permitted in the controller and the test should be adjusted to ensure they are permitted.

**Comment by Janell-Huyck** [comment]
https://ucdts.atlassian.net/browse/LIBAAEC-12
