### ISSUE TITLE
Fix mailer on servers

### ISSUE THREAD

**Issue by Janell-Huyck** [uclibs/aaec#421]
On deploying to production 4/16/2024, we discovered that while libappstest is running postfix and we had configured AAEC to work with postfix, our production server libapps is actually running sendmail instead of postfix.  Other applications are set up to run fine on either service, while aaec seems limited to postfix.  Glen and Samantha are going to be looking into whether or not they want to update libapps to postfix, but meanwhile it would be safest to adjust aaec to work correctly with either service.

**Comment by hortongn** [comment]
Apply the same fix from staff directory: https://github.com/uclibs/staff-directory-23/pull/164
Test by deploying to libappstest and ensuring emails send.

**Comment by Janell-Huyck** [comment]
https://ucdts.atlassian.net/browse/LIBAAEC-8
