### ISSUE TITLE
Add the Instructions section to the form

### ISSUE THREAD

**Issue by hortongn** [uclibs/aaec#5]
See the list of instructions at https://mailuc.sharepoint.com/:w:/r/sites/g-UCLAppDevTeam/Shared%20Documents/Applications/Life%20of%20the%20Mind/Life%20of%20the%20Mind%20submission%20form.docx?d=w457c41d2ea204888a1375574be9b7525&csf=1&e=zU6sFx

**Comment by bsp3ars** [comment]
Closed w/ #24
